### ISSUE TITLE
Can't open camera: java.lang.NullPointerException

### ISSUE THREAD

**Issue by duylong** [patzly/grocy-android#17]
Hi,

I have a FATAL exception:

```
FATAL EXCEPTION: main
Process: xyz.zedler.patrick.grocy, PID: 23073
java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.zedler.patrick.grocy/xyz.zedler.patrick.grocy.ScanBatchActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at xyz.zedler.patrick.grocy.ScanBatchActivity.onCreate(:2)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
	... 10 more
```
Android version: 7.1.2

**Comment by patzly** [comment]
Thanks for the log!
Please describe when the crash occurs (what you wanted to do), so I can probably reproduce it.

**Comment by duylong** [comment]
When I try to access the barcode scan ;)

**Comment by patzly** [comment]
Sorry, we cannot reproduce this bug as barcode scan works on all of our test devices.
You can try to run the project yourself and give the more precise logcat from Android Studio here, then we can fix the NullPointerException for sure.

**Comment by MrJohnZoidberg** [comment]
We discovered that the Xposed framework shows up in the RuntimeException – Could you try to access the barcode scanner after you switched off the framework (only to test this)?

**Comment by duylong** [comment]
Yes I have Xposed framework, I tested after switched off the framework and I have the same problem, sorry I can't uninstall the framework for the moment. 

Note: No problem with the Camera app.

**Comment by duylong** [comment]
Success when I use the camera in the product edit. The bug only appears on the stock overview page, when I touch on the icon for scan.

**Comment by patzly** [comment]
Please try out `v1.3.0` if the crash still occurs.

**Comment by duylong** [comment]
Bug disappeared: D

However, can we keep the landscape mode with the barcode scan?

**Comment by patzly** [comment]
Weird, but perfect!

> However, can we keep the landscape mode with the barcode scan?

That's another issue, maybe we will implement this in a future version.

**Comment by patzly** [comment]
@duylong thanks for the suggestion of landscape mode, this was easy to implement!

**Comment by duylong** [comment]
Great ! It's still better landscape mode on tablets :)
