### ISSUE TITLE
Failed to edit product

### ISSUE THREAD

**Issue by akitae** [patzly/grocy-android#224]
**App version**: 1.9.0

On the application, when I go to basic data, products. I select a product and click on modify, the application crashes.
Here are the logs :
```
-------- beginning of system
--------- beginning of crash
11-07 19:26:13.036 25738 25738 E AndroidRuntime: FATAL EXCEPTION: main
11-07 19:26:13.036 25738 25738 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 25738
11-07 19:26:13.036 25738 25738 E AndroidRuntime: java.lang.NumberFormatException: For input string: ""
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:627)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:650)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at d.a.a.a.h.h8.g2(SourceFile:7)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at d.a.a.a.h.h8.u1(Unknown Source:0)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at d.a.a.a.h.L1.a(Unknown Source:2)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at d.a.a.a.i.T$u.d(SourceFile:3)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at d.a.a.a.i.C.a(Unknown Source:2)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at d.a.a.a.i.b0.b(SourceFile:5)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at d.a.a.a.i.r.a(Unknown Source:6)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at d.a.a.a.i.M.a(Unknown Source:4)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at b.a.b.w.k.e(SourceFile:5)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at b.a.b.g$b.run(SourceFile:5)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7697)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
11-07 19:26:13.036 25738 25738 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by MrJohnZoidberg** [comment]
Does the product edit fragment appear for a short time after you clicked on edit? Or does the app crash right after you clicked on edit?

**Comment by akitae** [comment]
Edit product appear for a short time after click (less than one second) and the app crash.

**Comment by MrJohnZoidberg** [comment]
If the issue still occurs with `v1.9.1` (released soon), please reopen this issue. :-)
