### ISSUE TITLE
[v2.0.0][fixed] Refreshing Master data -> Quantity Units Crash

### ISSUE THREAD

**Issue by miketweaver** [patzly/grocy-android#331]
Refreshing the Quantity Units crashes the App

```
--------- beginning of main
02-08 14:27:01.399  3097  3097 E r.patrick.groc: Not starting debugger since process cannot load the jdwp agent.
02-08 14:34:09.524  4529  4529 E r.patrick.groc: Not starting debugger since process cannot load the jdwp agent.
02-08 14:35:06.155  4529  4632 E libc    : Access denied finding property "vendor.camera.aux.packagelist"
02-08 14:35:06.156  4529  4632 E libc    : Access denied finding property "vendor.camera.aux.packagelist"
02-08 14:35:06.156  4529  4632 E libc    : Access denied finding property "vendor.camera.hal1.packagelist"
02-08 14:35:06.187  4529  4632 E libc    : Access denied finding property "vendor.camera.aux.packagelist"
02-08 14:35:06.187  4529  4632 E libc    : Access denied finding property "vendor.camera.aux.packagelist"
--------- beginning of crash
02-08 14:36:13.936  4529  4840 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
02-08 14:36:13.936  4529  4840 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 4529
02-08 14:36:13.936  4529  4840 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
02-08 14:36:13.936  4529  4840 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
02-08 14:36:13.936  4529  4840 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
02-08 14:36:13.936  4529  4840 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
02-08 14:36:13.936  4529  4840 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
02-08 14:36:13.936  4529  4840 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
02-08 14:36:13.936  4529  4840 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-08 14:36:13.936  4529  4840 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-08 14:36:13.936  4529  4840 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
02-08 14:36:13.936  4529  4840 E AndroidRuntime: Caused by: java.lang.ClassCastException: xyz.zedler.patrick.grocy.model.QuantityUnit cannot be cast to xyz.zedler.patrick.grocy.model.Location
02-08 14:36:13.936  4529  4840 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.e.b$a.d(SourceFile:1)
02-08 14:36:13.936  4529  4840 E AndroidRuntime: 	at androidx.room.c.e(SourceFile:3)
02-08 14:36:13.936  4529  4840 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.e.b.c(SourceFile:3)
02-08 14:36:13.936  4529  4840 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.i.d$e.doInBackground(SourceFile:18)
02-08 14:36:13.936  4529  4840 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
02-08 14:36:13.936  4529  4840 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-08 14:36:13.936  4529  4840 E AndroidRuntime: 	... 4 more
02-08 14:36:18.655  4949  4949 E r.patrick.groc: Not starting debugger since process cannot load the jdwp agent.
02-08 14:36:23.528
```

Video:
![ezgif-2-b8f0a4888d36](https://user-images.githubusercontent.com/5581855/107286090-5950de80-6a1d-11eb-989e-ee443e67f0e5.gif)

**Comment by MrJohnZoidberg** [comment]
Thanks a lot! I can reproduce that.

**Comment by MrJohnZoidberg** [comment]
I forgot a `break` in the switch-case block... :)

**Comment by MrJohnZoidberg** [comment]
I will close this issue as soon as the next alpha is released, to prevent duplicates of this issue.
