### ISSUE TITLE
  [v2.0.0] Crash when consume/purchase is started in scan mode

### ISSUE THREAD

**Issue by matthiakl** [patzly/grocy-android#343]
When scanning an item in scan-mode, that exists in the database the app crashes.
Maybe related to #330 ?
```
02-09 16:50:48.524  1947  1947 E AndroidRuntime: FATAL EXCEPTION: main
02-09 16:50:48.524  1947  1947 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 1947
02-09 16:50:48.524  1947  1947 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1068)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at java.lang.Double.parseDouble(Double.java:547)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.model.y0.j(SourceFile:8)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.l.k4.b0(SourceFile:2)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.fragment.PurchaseFragment.S1(SourceFile:10)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.fragment.PurchaseFragment.X1(SourceFile:18)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.fragment.N2.a(SourceFile)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.l.y.c(SourceFile:1)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.l.r4.n(SourceFile:2)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.l.j3.c(SourceFile)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at androidx.lifecycle.LiveData.b(SourceFile:6)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at androidx.lifecycle.LiveData.c(SourceFile:8)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at androidx.lifecycle.LiveData.m(SourceFile:4)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at androidx.lifecycle.p.m(SourceFile:1)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.l.r4.m(SourceFile:2)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.l.Y3.i(SourceFile:1)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.l.k4.S(SourceFile:63)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.l.m1.a(SourceFile)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.h.j.a(SourceFile:5)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.h.a.a(SourceFile)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.m.e.a(SourceFile:3)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at b.a.b.w.k.e(SourceFile:5)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at b.a.b.g$b.run(SourceFile:5)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
02-09 16:50:48.524  1947  1947 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by MrJohnZoidberg** [comment]
Thanks for your support, this is already tracked in #330 . I hope I can reproduce it.
