### ISSUE TITLE
Chore list crash

### ISSUE THREAD

**Issue by longshot338** [patzly/grocy-android#594]
When using latest docker image version from linuxserver/grocy. Selecting chores in app crashes application with no user viewable error.

Server version 3.3.2, application version on Android of 2.3.0

**Comment by ANBAL534** [comment]
I can confirm, it gives an error of UnparseableDate:

<details><summary>Logs</summary>
<p>
```java
   --------- beginning of main
12-06 11:19:20.941 22793 22793 E BufferQueueProducer: Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found.
12-06 11:19:20.986 22793 22793 E DateUtil: getDaysFromNow: java.text.ParseException: Unparseable date: "2022-12-24"
12-06 11:19:21.411 22793 22793 E DateUtil: getDaysFromNow: java.text.ParseException: Unparseable date: "2022-12-24"
12-06 11:19:50.962 22793 22793 E DateUtil: getDaysFromNow: java.text.ParseException: Unparseable date: "2022-12-24"
12-06 11:19:50.963 22793 22793 E DateUtil: getDaysFromNow: java.text.ParseException: Unparseable date: "2022-12-24"
12-06 11:19:50.964 22793 22793 E DateUtil: getDate: 
--------- beginning of crash
12-06 11:19:50.965 22793 22793 E AndroidRuntime: FATAL EXCEPTION: main
12-06 11:19:50.965 22793 22793 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 22793
12-06 11:19:50.965 22793 22793 E AndroidRuntime: io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.Date.compareTo(java.util.Date)' on a null object reference
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:2)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:2)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:4)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:3)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:1)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at android.os.Handler.handleCallback(Handler.java:942)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:99)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at android.os.Looper.loopOnce(Looper.java:226)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:313)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at android.app.ActivityThread.main(ActivityThread.java:8772)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at java.lang.reflect.Method.invoke(Native Method)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
12-06 11:19:50.965 22793 22793 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.Date.compareTo(java.util.Date)' on a null object reference
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at xyz.zedler.patrick.grocy.util.SortUtil$$ExternalSyntheticLambda19.compare(R8$$SyntheticClass:7)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at java.util.TimSort.binarySort(TimSort.java:296)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at java.util.TimSort.sort(TimSort.java:221)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at java.util.Arrays.sort(Arrays.java:1495)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at java.util.ArrayList.sort(ArrayList.java:1470)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at java.util.Collections.sort(Collections.java:206)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at xyz.zedler.patrick.grocy.viewmodel.ChoresViewModel.updateFilteredChoreEntries(ChoresViewModel.java:23)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at xyz.zedler.patrick.grocy.viewmodel.ChoresViewModel$$ExternalSyntheticLambda3.actionFinished(R8$$SyntheticClass:28)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at xyz.zedler.patrick.grocy.bottomappbar.BottomAppBar$$ExternalSyntheticLambda0.accept(Unknown Source:6)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:1)
12-06 11:19:50.965 22793 22793 E AndroidRuntime:  ... 10 more
12-06 11:22:39.541 23544 23544 E r.patrick.grocy: Not starting debugger since process cannot load the jdwp agent.
12-06 11:22:39.633 23544 23544 E BufferQueueProducer: Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found.
12-06 11:22:40.607 23544 23544 E DateUtil: getDaysFromNow: java.text.ParseException: Unparseable date: "2022-12-24"
12-06 11:22:41.062 23544 23544 E DateUtil: getDaysFromNow: java.text.ParseException: Unparseable date: "2022-12-24"
```

</p>
</details>

**Comment by MrJohnZoidberg** [comment]
Does this crash also occur in the latest [nightly build](https://github.com/patzly/grocy-android/releases/tag/nightly) of our app?

**Comment by dominiczedler** [comment]
@longshot338 Ping :)

**Comment by dominiczedler** [comment]
Nobody can test it?

**Comment by ANBAL534** [comment]
Can confirm, the bug is not present in latest nightly build :+1:
