### ISSUE TITLE
Crash after transaction when using ML Kit

### ISSUE THREAD

**Issue by patzly** [patzly/grocy-android#639]
1. Open purchase page in scan mode
2. Scan a product to fill the form
3. Tap on Purchase -> Crash

The transaction is already finished on the server at this point, so it has to do with restarting the scanner for the next product or so. Could be an internal error of the current version of androidx.camera.

> 01-18 00:34:08.939 16881 16881 E AndroidRuntime: FATAL EXCEPTION: main
01-18 00:34:08.939 16881 16881 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 16881
01-18 00:34:08.939 16881 16881 E AndroidRuntime: java.lang.IllegalArgumentException: The detector does not exist
01-18 00:34:08.939 16881 16881 E AndroidRuntime: 	at com.google.android.gms.common.internal.Preconditions.checkArgument(com.google.android.gms:play-services-basement@@18.1.0:2)
01-18 00:34:08.939 16881 16881 E AndroidRuntime: 	at androidx.camera.mlkit.vision.MlKitAnalyzer$Result.checkDetectorExists(MlKitAnalyzer.java:361)
01-18 00:34:08.939 16881 16881 E AndroidRuntime: 	at androidx.camera.mlkit.vision.MlKitAnalyzer$Result.getValue(MlKitAnalyzer.java:332)
01-18 00:34:08.939 16881 16881 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.scanner.EmbeddedFragmentScannerMLKit.lambda$startScannerIfVisible$4$xyz-zedler-patrick-grocy-scanner-EmbeddedFragmentScannerMLKit(EmbeddedFragmentScannerMLKit.java:254)
01-18 00:34:08.939 16881 16881 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.scanner.EmbeddedFragmentScannerMLKit$$ExternalSyntheticLambda2.accept(Unknown Source:4)
01-18 00:34:08.939 16881 16881 E AndroidRuntime: 	at androidx.camera.mlkit.vision.MlKitAnalyzer.lambda$detectRecursively$0$androidx-camera-mlkit-vision-MlKitAnalyzer(MlKitAnalyzer.java:206)
01-18 00:34:08.939 16881 16881 E AndroidRuntime: 	at androidx.camera.mlkit.vision.MlKitAnalyzer$$ExternalSyntheticLambda0.run(Unknown Source:8)
01-18 00:34:08.939 16881 16881 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
01-18 00:34:08.939 16881 16881 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-18 00:34:08.939 16881 16881 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-18 00:34:08.939 16881 16881 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-18 00:34:08.939 16881 16881 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
01-18 00:34:08.939 16881 16881 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-18 00:34:08.939 16881 16881 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-18 00:34:08.939 16881 16881 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by patzly** [comment]
It's still happening for me... Hopefully it's solved with the next camerax version.

**Comment by patzly** [comment]
Closed because it's not happening anymore, CameraX update solved it as it was an internal bug.
