### ISSUE TITLE
Unable to do multiple chores

### ISSUE THREAD

**Issue by matthiakl** [patzly/grocy-android#686]
After I mark one chore as done, the popup shows and the chore is moved to the bottom. However, if I try to resolve a second one afterwards, the popup shows, but nothing else happens. I have to reenter the page and do the second one again, to properly record it in the database.

**Comment by dominiczedler** [comment]
Sorry, I cannot reproduce this issue, can you reproduce it with the demo server too?

**Comment by matthiakl** [comment]
Yes, I can reproduce it with the demo server. The second chore needs a second activation to update correctly. My steps:
1. Make sure there are at least two chores due today
2. Swipe one to the right and press the "track" button
    - Popup "Ausführung erfasst"
    - Due date updates
4. Swipe the next chore to the right and press "track"
    - Popup "Ausführung erfasst"
    - Nothing else changes
5. Repeat step 4
    - Popup "Ausführung erfasst"
    - Now the due date updates

**Comment by matthiakl** [comment]
In the log I see this error, but I am not sure, whether it is related:
```
08 17:25:27.421 11761 11761 E AndroidRuntime: FATAL EXCEPTION: main
06-08 17:25:27.421 11761 11761 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 11761
06-08 17:25:27.421 11761 11761 E AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {xyz.zedler.patrick.grocy/xyz.zedler.patrick.grocy.activity.SplashActivity}: java.lang.NullPointerException: Attempt to read from field 'java.util.Timer xyz.zedler.patrick.grocy.util.NetUtil.hassSessionTimer' on a null object reference
06-08 17:25:27.421 11761 11761 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3780)
06-08 17:25:27.421 11761 11761 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3746)
06-08 17:25:27.421 11761 11761 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3720)
06-08 17:25:27.421 11761 11761 E AndroidRuntime: 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3694)
06-08 17:25:27.421 11761 11761 E AndroidRuntime: 	at android.app.ActivityThread.-wrap16(ActivityThread.java)
06-08 17:25:27.421 11761 11761 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508)
06-08 17:25:27.421 11761 11761 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-08 17:25:27.421 11761 11761 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-08 17:25:27.421 11761 11761 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
06-08 17:25:27.421 11761 11761 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-08 17:25:27.421 11761 11761 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-08 17:25:27.421 11761 11761 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-08 17:25:27.421 11761 11761 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.Timer xyz.zedler.patrick.grocy.util.NetUtil.hassSessionTimer' on a null object reference
06-08 17:25:27.421 11761 11761 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.activity.MainActivity.onPause(MainActivity.java:3)
06-08 17:25:27.421 11761 11761 E AndroidRuntime: 	at android.app.Activity.performPause(Activity.java:6824)
06-08 17:25:27.421 11761 11761 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1323)
06-08 17:25:27.421 11761 11761 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3769)
06-08 17:25:27.421 11761 11761 E AndroidRuntime: 	... 11 more
```
