### ISSUE TITLE
App crashig after latest release (Product stock overview popup)

### ISSUE THREAD

**Issue by alkuzman** [patzly/grocy-android#699]
The app crashes after opening a stock overview popup. 

Server: 3.3.2 Docker

```
05-19 19:31:47.670 19472 19472 I ViewRootImpl@bd7094d[PopupWindow:c7d00e4]:   pfl=42018000
05-19 19:31:47.670 19472 19472 I ViewRootImpl@bd7094d[PopupWindow:c7d00e4]:   bhv=DEFAULT
05-19 19:31:47.670 19472 19472 I ViewRootImpl@bd7094d[PopupWindow:c7d00e4]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR naviIconColor=0
05-19 19:31:47.670 19472 19472 I ViewRootImpl@bd7094d[PopupWindow:c7d00e4]:   sfl=20000}
05-19 19:31:47.679 19472 19472 I ViewRootImpl@bd7094d[PopupWindow:c7d00e4]: updateBlastSurfaceIfNeeded mBlastBufferQueue=0xb4000075ac081590 isSameSurfaceControl=true
05-19 19:31:47.680 19472 19472 I BLASTBufferQueue: update, w= 585 h= 348 mName = ViewRootImpl@bd7094d[PopupWindow:c7d00e4] mNativeObject= 0xb4000075ac081590 sc.mNativeObject= 0xb40000753c200730 format= -3 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2898 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 
05-19 19:31:47.680 19472 19472 I ViewRootImpl@bd7094d[PopupWindow:c7d00e4]: Relayout returned: old=(0,1772,551,2086) new=(0,1772,551,2086) req=(551,314)0 dur=9 res=0x0 s={true 0xb40000763c066ae0} ch=false seqId=0
05-19 19:31:47.681 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: performTraversals params={(294,1637)(786x449) gr=TOP START CENTER DISPLAY_CLIP_VERTICAL sim={state=unchanged adjust=resize} ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT surfaceInsets=Rect(17, 17 - 17, 17) (manual)
05-19 19:31:47.681 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]:   fl=41860200
05-19 19:31:47.681 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]:   pfl=2018000
05-19 19:31:47.681 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]:   bhv=DEFAULT
05-19 19:31:47.681 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR naviIconColor=0
05-19 19:31:47.681 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]:   sfl=20000}
05-19 19:31:47.681 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: performTraversals mFirst=true windowShouldResize=true viewVisibilityChanged=false mForceNextWindowRelayout=false params={(294,1637)(786x449) gr=TOP START CENTER DISPLAY_CLIP_VERTICAL sim={state=unchanged adjust=resize} ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT surfaceInsets=Rect(17, 17 - 17, 17) (manual)
05-19 19:31:47.681 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]:   fl=41860200
05-19 19:31:47.681 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]:   pfl=2018000
05-19 19:31:47.681 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]:   bhv=DEFAULT
05-19 19:31:47.681 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR IME naviIconColor=0
05-19 19:31:47.681 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]:   sfl=20000}
05-19 19:31:47.686 19472 19562 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: Resizing android.view.ViewRootImpl@9fcf3b3: frame = [294,1637][1080,2086] reportDraw = true forceLayout = false syncSeqId = 0
05-19 19:31:47.688 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: updateBlastSurfaceIfNeeded mBlastBufferQueue=null isSameSurfaceControl=false
05-19 19:31:47.689 19472 19472 I BLASTBufferQueue: new BLASTBufferQueue, mName= ViewRootImpl@a41bd96[PopupWindow:6d624b1] mNativeObject= 0xb4000075ac0802d0 sc.mNativeObject= 0xb40000753c211980 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2909 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 android.view.Choreographer$CallbackRecord.run:1309 android.view.Choreographer.doCallbacks:923 android.view.Choreographer.doFrame:852 android.view.Choreographer$FrameDisplayEventReceiver.run:1283 
05-19 19:31:47.689 19472 19472 I BLASTBufferQueue: update, w= 820 h= 483 mName = ViewRootImpl@a41bd96[PopupWindow:6d624b1] mNativeObject= 0xb4000075ac0802d0 sc.mNativeObject= 0xb40000753c211980 format= -3 caller= android.graphics.BLASTBufferQueue.<init>:84 android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2909 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 
05-19 19:31:47.689 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: Relayout returned: old=(294,2086,1080,2086) new=(294,1637,1080,2086) req=(786,449)0 dur=7 res=0x3 s={true 0xb40000763c0648d0} ch=true seqId=0
05-19 19:31:47.689 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: mThreadedRenderer.initialize() mSurface={isValid=true 0xb40000763c0648d0} hwInitialized=true
05-19 19:31:47.698 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: reportNextDraw android.view.ViewRootImpl.performTraversals:4438 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 android.view.Choreographer$CallbackRecord.run:1309 
05-19 19:31:47.699 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: Setup new sync id=0
05-19 19:31:47.699 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: Setting syncFrameCallback
05-19 19:31:47.699 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: registerCallbacksForSync syncBuffer=false
05-19 19:31:47.700 19472 19646 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: Received frameDrawingCallback syncResult=0 frameNum=1.
05-19 19:31:47.700 19472 19646 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: Setting up sync and frameCommitCallback
05-19 19:31:47.703 19472 19583 I BLASTBufferQueue: [ViewRootImpl@a41bd96[PopupWindow:6d624b1]#26](f:0,a:0) onFrameAvailable the first frame is available
05-19 19:31:47.703 19472 19583 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
05-19 19:31:47.704 19472 19583 W Parcel  : Expecting binder but got null!
05-19 19:31:47.704 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: onSyncComplete
05-19 19:31:47.705 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: setupSync seqId=0 mSyncId=0 fn=1 caller=android.view.ViewRootImpl$$ExternalSyntheticLambda11.accept:6 android.window.SurfaceSyncer.lambda$setupSync$1$android-window-SurfaceSyncer:128 android.window.SurfaceSyncer$$ExternalSyntheticLambda1.accept:8 android.window.SurfaceSyncer$SyncSet.checkIfSyncIsComplete:382 android.window.SurfaceSyncer$SyncSet.markSyncReady:359 android.window.SurfaceSyncer.markSyncReady:151 android.view.ViewRootImpl.performTraversals:4503 
05-19 19:31:47.705 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: reportDrawFinished seqId=0 mSyncId=-1 fn=1 mSurfaceChangedTransaction=0xb40000756c065bb0
05-19 19:31:47.708 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: handleResized, msg = 5 frames=ClientWindowFrames{frame=[294,1637][1080,2086] display=[-100000,-100000][100000,100000] parentFrame=[0,0][0,0] parentClippedByDisplayCutout=false} forceNextWindowRelayout=false displayId=0 resizeMode=-1 frameChanged=false displayFrameChanged=false configChanged=false displayChanged=false
05-19 19:31:47.708 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: handleResized mSyncSeqId = 0
05-19 19:31:47.708 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: reportNextDraw android.view.ViewRootImpl.handleResized:2450 android.view.ViewRootImpl.-$$Nest$mhandleResized:0 android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:6728 android.view.ViewRootImpl$ViewRootHandler.handleMessage:6697 android.os.Handler.dispatchMessage:106 
05-19 19:31:47.708 19472 19472 I ViewRootImpl@bd7094d[PopupWindow:c7d00e4]: MSG_WINDOW_FOCUS_CHANGED 0 0
05-19 19:31:47.720 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: Setup new sync id=1
05-19 19:31:47.720 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: Setting syncFrameCallback
05-19 19:31:47.720 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: registerCallbacksForSync syncBuffer=false
05-19 19:31:47.721 19472 19645 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: Received frameDrawingCallback syncResult=0 frameNum=3.
05-19 19:31:47.721 19472 19645 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: Setting up sync and frameCommitCallback
05-19 19:31:47.723 19472 19583 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: Received frameCommittedCallback lastAttemptedDrawFrameNum=3 didProduceBuffer=true
05-19 19:31:47.723 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: onSyncComplete
05-19 19:31:47.723 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: setupSync seqId=0 mSyncId=1 fn=3 caller=android.view.ViewRootImpl$$ExternalSyntheticLambda11.accept:6 android.window.SurfaceSyncer.lambda$setupSync$1$android-window-SurfaceSyncer:128 android.window.SurfaceSyncer$$ExternalSyntheticLambda1.accept:8 android.window.SurfaceSyncer$SyncSet.checkIfSyncIsComplete:382 android.window.SurfaceSyncer$SyncSet.markSyncReady:359 android.window.SurfaceSyncer.markSyncReady:151 android.view.ViewRootImpl.performTraversals:4503 
05-19 19:31:47.726 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: reportDrawFinished seqId=0 mSyncId=-1 fn=3 mSurfaceChangedTransaction=0xb40000756c065bb0
05-19 19:31:47.727 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: MSG_WINDOW_FOCUS_CHANGED 1 0
05-19 19:31:47.727 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb40000763c0648d0}
05-19 19:31:48.023 19472 19472 I ViewRootImpl@bd7094d[PopupWindow:c7d00e4]: dispatchDetachedFromWindow
05-19 19:31:48.495 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: ViewPostIme pointer 0
05-19 19:31:48.567 19472 19472 I ViewRootImpl@a41bd96[PopupWindow:6d624b1]: ViewPostIme pointer 1
```

**Comment by Choukajohn** [comment]
Same here on Pixel 6 Android 13
Error log :

```
--------- beginning of crash
05-20 13:26:02.927 28708 28708 E AndroidRuntime: FATAL EXCEPTION: main
05-20 13:26:02.927 28708 28708 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 28708
05-20 13:26:02.927 28708 28708 E AndroidRuntime: java.lang.ClassCastException
05-20 13:26:02.927 28708 28708 E AndroidRuntime: 	at androidx.camera.core.impl.Config$-CC.m(SourceFile:34)
05-20 13:26:02.927 28708 28708 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.fragment.bottomSheetDialog.ProductOverviewBottomSheet$$ExternalSyntheticLambda2.onResponse(SourceFile:41)
05-20 13:26:02.927 28708 28708 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.helper.DownloadHelper$$ExternalSyntheticLambda7.onResponse(Unknown Source:9)
05-20 13:26:02.927 28708 28708 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.web.CustomStringRequest$$ExternalSyntheticLambda0.onResponse(SourceFile:27)
05-20 13:26:02.927 28708 28708 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.web.CustomStringRequest.deliverResponse(SourceFile:11)
05-20 13:26:02.927 28708 28708 E AndroidRuntime: 	at com.google.android.gms.common.images.zaa.run(SourceFile:210)
05-20 13:26:02.927 28708 28708 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
05-20 13:26:02.927 28708 28708 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-20 13:26:02.927 28708 28708 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-20 13:26:02.927 28708 28708 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-20 13:26:02.927 28708 28708 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7884)
05-20 13:26:02.927 28708 28708 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-20 13:26:02.927 28708 28708 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-20 13:26:02.927 28708 28708 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
05-20 13:26:04.112 29240 29240 E r.patrick.grocy: Not starting debugger since process cannot load the jdwp agent.
```

**Comment by dominiczedler** [comment]
Sorry for the weird crash, we will release a new version quickly.
