### ISSUE TITLE
Network Error on Transfering product 

### ISSUE THREAD

**Issue by TurnrDev** [patzly/grocy-android#751]
I am getting a network error when trying to transfer.

These are the logs I get:

```
Network error

com.android.volley.ClientError
	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:193)
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

```

Which given they're all from the volley package and not yours probably isn't much help. 

I run server 4.0.1
I tested on play store version 3.3.0 and on the github nightly 20230810 and got the error on both.

I've no idea if this is a grocy-android error or a proxy API error. 

Shall I fire up a copy of Android studio and connect to my device in debug mode to see if that gives me any more logs?

**Comment by TurnrDev** [comment]
I've turned on debugging and seen that this is coming from the grocy API, not the app. I'll close this and non-issue

**Comment by TurnrDev** [comment]
Manually calling the API I don't get an issue, I wonder if this is a conversion issue.
