### ISSUE TITLE
Networkerrors since Grocy 4.0.3

### ISSUE THREAD

**Issue by mmtg5** [patzly/grocy-android#774]
After updating grocy from 4.0.2 to 4.0.3 the App causes network errors on e.g. adding or editing products

com.android.volley.ClientError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:251)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:51)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:6)

**Comment by patzly** [comment]
Hi, this has already been addressed in #772 as the app was not actively supporting this server version and the dev of the server application accidentally made a braking change in the latest release.
