### ISSUE TITLE
Network errore on any action request

### ISSUE THREAD

**Issue by igor-cali** [patzly/grocy-android#776]
Grocy android v4.0.2
Grocy server v4.0.3
Network error:

```
com.android.volley.ServerError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:257)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:51)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:6)
```

No action change can be completed (e.g. purchase item, consumer item, do chore, etc.

**Comment by igor-cali** [comment]
Thanks. Versione corrected in the reporter. I will wait for v3.3.2 release om F-droid.
