### ISSUE TITLE
Error while adding new product

### ISSUE THREAD

**Issue by dezok666** [patzly/grocy-android#786]
While adding new product via application I receive below error:
```
Network error

com.android.volley.ClientError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:251)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:51)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:6)
```

**Comment by dominiczedler** [comment]
Please check for a new version of our app first. This was an error in 3.3.1 and 3.3.2 is the latest version, maybe you use F-Droid and there is currently a problem with this update.

**Comment by dezok666** [comment]
Updated app, similar error:
```
Network error

com.android.volley.ClientError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:251)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:51)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:6)

```

**Comment by patzly** [comment]
Which app version do you use now?

**Comment by dezok666** [comment]
Now it's 3.3.2
