### ISSUE TITLE
Crash when opening App

### ISSUE THREAD

**Issue by fkuzun** [patzly/grocy-android#789]
After update to Android 14 the App crashes on opening with the following Error:

```
type: crash
osVersion: google/bluejay/bluejay:14/UP1A.231005.007/2023101300:user/release-keys
package: xyz.zedler.patrick.grocy:50
process: xyz.zedler.patrick.grocy
processUptime: 161 + 200 ms
installer: com.android.vending

java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.zedler.patrick.grocy/xyz.zedler.patrick.grocy.activity.SplashActivity}: java.lang.SecurityException: xyz.zedler.patrick.grocy: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3793)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3933)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.SecurityException: xyz.zedler.patrick.grocy: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5699)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1873)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1813)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1801)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
	at info.guardianproject.netcipher.proxy.OrbotHelper.init(OrbotHelper.java:143)
	at xyz.zedler.patrick.grocy.activity.MainActivity.onCreate(MainActivity.java:151)
	at xyz.zedler.patrick.grocy.activity.SplashActivity.onCreate(SplashActivity.java:16)
	at android.app.Activity.performCreate(Activity.java:8651)
	at android.app.Activity.performCreate(Activity.java:8629)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1461)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3775)
	... 14 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13988)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2578)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2724)
	at android.os.Binder.execTransactInternal(Binder.java:1368)
	at android.os.Binder.execTransact(Binder.java:1299)


```

**Comment by fkuzun** [comment]
Some more info: clearing app storage will stop the crash on opening. It reoccurs when the "Use Tor" option is enabled

**Comment by dominiczedler** [comment]
Thanks!
