### ISSUE TITLE
If AuthFailureError, open browser to allow authentication

### ISSUE THREAD

**Issue by jjgmckenzie** [patzly/grocy-android#829]
I have Grocy running behind Authelia, which means I cannot use the app; as I receive an AuthFailureError. 

Instead; a browser page could be opened where auth is performed, then the app could function as normal.

I would be happy to investigate making a PR for this if this would be adopted

**Comment by manuel-rw** [comment]
Also interested in this 👍

**Comment by dominiczedler** [comment]
Has Authelia some kind of token implementation, so that the app could fetch a token and use it in further connections after that?

**Comment by benjamin3322** [comment]
Hello, I'm also interested in this.

I use cloudflare to secure applications that are publicly available.

To secure an application we have multiple possibilities (not exaustive):

- mTLS: A client certificate is required to communicate with the application through the internet (I think I see another issue about allowing a client certificate to communicate with HA/Grocy).
- Additional authentication using an identity provider. In such case, a login HTML page (authentication form of the identity provider) is returned.

The later causes an error: 
```
Erreur : Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
	at org.json.JSON.typeMismatch(JSON.java:112)
	at org.json.JSONObject.<init>(JSONObject.java:172)
	at org.json.JSONObject.<init>(JSONObject.java:185)
	at androidx.camera.view.PreviewView$1$$ExternalSyntheticLambda2.onResponse(R8$$SyntheticClass:18)
	at xyz.zedler.patrick.grocy.helper.DownloadHelper$$ExternalSyntheticLambda11.onResponse(R8$$SyntheticClass:1)
	at xyz.zedler.patrick.grocy.web.CustomStringRequest$$ExternalSyntheticLambda0.onResponse(R8$$SyntheticClass:17)
	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:11)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:27)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

I think HomeAssistant handle both cases when connecting with the compagnon app.

**Comment by patzly** [comment]
I will close this issue for now. Because my twin brother Dominic switched to Apple devices a while ago and doesn't actively use Grocy himself, he has withdrawn from the Grocy Android project. This means that I am now the sole maintainer of this now large project. I will continue to develop the app alongside my studies, my job and my other projects, as my free time allows, but l haven't enough time for big changes like this. I hope you understand, an update with many improvements is coming very soon and maybe you can enjoy some of my other app projects I spend my free time on alongside Grocy Android!
This issue may be re-opened in the future if you want to contribute with a pull request and need some room for discussion. Pull requests are happily accepted if they are working!

**Comment by patzly** [comment]
As I said, it can be reopened in the future if someone wants to address it, but when you think it helps if it's open I will reopen it.

**Comment by firewallzer0** [comment]
I am also interested in this feature, I will start going through it and seeing where I can help. I am not much of a programmer more of a tinker-er. But I have some friends I might be able to rope into helping me. 

My interest is in getting this working with cloudflare tunnels using Authentik (https://goauthentik.io/) which provides an OpenID. There is a lot for me to learn so don't expect anything soon but I will see what I can do, or can't...
