### ISSUE TITLE
App crashes when editing Master Data

### ISSUE THREAD

**Issue by YoMamasNerd** [patzly/grocy-android#831]
When adding new items in the Master Data section the app crashes. Data is still written. This but is reproducible on my end.

```
--------- beginning of crash
01-26 23:50:07.751 14045 14045 E AndroidRuntime: FATAL EXCEPTION: main
01-26 23:50:07.751 14045 14045 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 14045
01-26 23:50:07.751 14045 14045 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'androidx.core.view.WindowInsetsAnimationCompat$Impl androidx.core.view.WindowInsetsAnimationCompat.mImpl' on a null object reference in method 'androidx.core.view.WindowInsetsCompat xyz.zedler.patrick.grocy.util.UiUtil$1.onProgress(androidx.core.view.WindowInsetsCompat, java.util.List)'
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.util.UiUtil$1.onProgress(UiUtil.java:13)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at androidx.core.view.WindowInsetsAnimationCompat$Impl30$ProxyCallback.onProgress(WindowInsetsAnimationCompat.java:72)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.view.View.dispatchWindowInsetsAnimationProgress(View.java:12162)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7614)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.view.ViewRootInsetsControllerHost.dispatchWindowInsetsAnimationProgress(ViewRootInsetsControllerHost.java:108)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.view.InsetsController.lambda$new$3(InsetsController.java:818)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.view.InsetsController.$r8$lambda$meqKUiuVHZJFS86fhQQzBBmdABw(Unknown Source:0)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.view.InsetsController$$ExternalSyntheticLambda9.run(D8$$SyntheticClass:0)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1399)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:935)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8501)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
01-26 23:50:07.751 14045 14045 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
--------- beginning of main
01-26 23:50:09.245 14279 14279 E r.patrick.grocy: Not starting debugger since process cannot load the jdwp agent.
01-26 23:50:25.615 14279 14279 E AndroidRuntime: FATAL EXCEPTION: main
01-26 23:50:25.615 14279 14279 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 14279
01-26 23:50:25.615 14279 14279 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'androidx.core.view.WindowInsetsAnimationCompat$Impl androidx.core.view.WindowInsetsAnimationCompat.mImpl' on a null object reference in method 'androidx.core.view.WindowInsetsCompat xyz.zedler.patrick.grocy.util.UiUtil$1.onProgress(androidx.core.view.WindowInsetsCompat, java.util.List)'
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.util.UiUtil$1.onProgress(UiUtil.java:13)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at androidx.core.view.WindowInsetsAnimationCompat$Impl30$ProxyCallback.onProgress(WindowInsetsAnimationCompat.java:72)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.view.View.dispatchWindowInsetsAnimationProgress(View.java:12162)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7614)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.view.ViewRootInsetsControllerHost.dispatchWindowInsetsAnimationProgress(ViewRootInsetsControllerHost.java:108)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.view.InsetsController.lambda$new$3(InsetsController.java:818)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.view.InsetsController.$r8$lambda$meqKUiuVHZJFS86fhQQzBBmdABw(Unknown Source:0)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.view.InsetsController$$ExternalSyntheticLambda9.run(D8$$SyntheticClass:0)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1399)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:935)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8501)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
01-26 23:50:25.615 14279 14279 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
01-26 23:50:27.697 14403 14403 E r.patrick.grocy: Not starting debugger since process cannot load the jdwp agent.
01-26 23:50:49.826 14403 14403 E AndroidRuntime: FATAL EXCEPTION: main
01-26 23:50:49.826 14403 14403 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 14403
01-26 23:50:49.826 14403 14403 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'androidx.core.view.WindowInsetsAnimationCompat$Impl androidx.core.view.WindowInsetsAnimationCompat.mImpl' on a null object reference in method 'androidx.core.view.WindowInsetsCompat xyz.zedler.patrick.grocy.util.UiUtil$1.onProgress(androidx.core.view.WindowInsetsCompat, java.util.List)'
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.util.UiUtil$1.onProgress(UiUtil.java:13)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at androidx.core.view.WindowInsetsAnimationCompat$Impl30$ProxyCallback.onProgress(WindowInsetsAnimationCompat.java:72)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.view.View.dispatchWindowInsetsAnimationProgress(View.java:12162)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7614)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.view.ViewRootInsetsControllerHost.dispatchWindowInsetsAnimationProgress(ViewRootInsetsControllerHost.java:108)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.view.InsetsController.lambda$new$3(InsetsController.java:818)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.view.InsetsController.$r8$lambda$meqKUiuVHZJFS86fhQQzBBmdABw(Unknown Source:0)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.view.InsetsController$$ExternalSyntheticLambda9.run(D8$$SyntheticClass:0)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1399)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:935)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8501)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
01-26 23:50:49.826 14403 14403 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
01-26 23:50:51.076 14551 14551 E r.patrick.grocy: Not starting debugger since process cannot load the jdwp agent.
01-26 23:52:33.276 14551 14551 E AndroidRuntime: FATAL EXCEPTION: main
01-26 23:52:33.276 14551 14551 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 14551
01-26 23:52:33.276 14551 14551 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'androidx.core.view.WindowInsetsAnimationCompat$Impl androidx.core.view.WindowInsetsAnimationCompat.mImpl' on a null object reference in method 'androidx.core.view.WindowInsetsCompat xyz.zedler.patrick.grocy.util.UiUtil$1.onProgress(androidx.core.view.WindowInsetsCompat, java.util.List)'
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.util.UiUtil$1.onProgress(UiUtil.java:13)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at androidx.core.view.WindowInsetsAnimationCompat$Impl30$ProxyCallback.onProgress(WindowInsetsAnimationCompat.java:72)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.view.View.dispatchWindowInsetsAnimationProgress(View.java:12162)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7614)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7620)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.view.ViewRootInsetsControllerHost.dispatchWindowInsetsAnimationProgress(ViewRootInsetsControllerHost.java:108)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.view.InsetsController.lambda$new$3(InsetsController.java:818)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.view.InsetsController.$r8$lambda$meqKUiuVHZJFS86fhQQzBBmdABw(Unknown Source:0)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.view.InsetsController$$ExternalSyntheticLambda9.run(D8$$SyntheticClass:0)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1399)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:935)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8501)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
01-26 23:52:33.276 14551 14551 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
01-26 23:52:35.800 14958 14958 E r.patrick.grocy: Not starting debugger since process cannot load the jdwp agent.
01-26 23:52:46.980 14958 14958 E ViewUtil: icon animation requires AnimVectorDrawable
01-26 23:52:50.361 14958 14958 E ViewUtil: icon animation requires AnimVectorDrawable
```

**Comment by BuyakaBuyak** [comment]
Same here. 
Fresh grocy Installation.
whenever I save a changw to the Master data (Stammdaten) the app crashes yet still writes the changes to the server.

**Comment by patzly** [comment]
Very strange, I cannot reproduce it on any of my devices :/
Thanks for the logcat, but sadly it isn't very helpful because it points on an internal field which seems to be not initialized on your devices, but when it works on other devices like mine it's very hard to find the cause I think...

**Comment by patzly** [comment]
Maybe there is a setting required to turn off keyboard animation as a workaround, as the animation callback causes the crash.

**Comment by YoMamasNerd** [comment]
I'm running the app on my Google Pixel 6 with the latest Android 14 beta.
The server is running on my local TrueNas server.
Is there something or some log that would help you?

**Comment by patzly** [comment]
@YoMamasNerd I testet it yesterday on my Pixel 6 with Android 14 Beta, too, but the different behavior is hard to explain...  Could you please give the specific steps you can perform on the demo server to reproduce the issue? Maybe I miss something?

**Comment by YoMamasNerd** [comment]
[Video of action to cause the crash](http://sync.hometopf.de/f/ad960b18b8724c6caf71/)

**Comment by patzly** [comment]
Ah now I'm able to reproduce it with locations! I only tested it with products, but they seem to work.

**Comment by YoMamasNerd** [comment]
Great, glad I could help a little bit

**Comment by X-Nightmare-X** [comment]
The nightly build (downloaded 1 day ago) has the same failure on my Galaxy S21.
Commented it on Google Play too.
I will look for the workaround with the keyboard.
It safes the changes but clothes as mentioned above.

**Comment by patzly** [comment]
@X-Nightmare-X Can you please attach your crash log from the nightly build?

**Comment by patzly** [comment]
@X-Nightmare-X This would be important as we want to release the next version😅

**Comment by YoMamasNerd** [comment]
> @X-Nightmare-X Can you please attach your crash log from the nightly build?

I'm able to reproduce the crash with the latest nightly too. 

```
--------- beginning of crash
02-21 12:28:00.908 31609 31609 E AndroidRuntime: FATAL EXCEPTION: main
02-21 12:28:00.908 31609 31609 E AndroidRuntime: Process: xyz.zedler.patrick.grocy.nightly.debug, PID: 31609
02-21 12:28:00.908 31609 31609 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'float androidx.core.view.WindowInsetsAnimationCompat.getInterpolatedFraction()' on a null object reference
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.util.UiUtil$1.onProgress(UiUtil.java:334)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at androidx.core.view.WindowInsetsAnimationCompat$Impl30$ProxyCallback.onProgress(WindowInsetsAnimationCompat.java:1072)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.view.View.dispatchWindowInsetsAnimationProgress(View.java:12173)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7624)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7630)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7630)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7630)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7630)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7630)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.view.ViewRootInsetsControllerHost.dispatchWindowInsetsAnimationProgress(ViewRootInsetsControllerHost.java:108)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.view.InsetsController.lambda$new$3(InsetsController.java:818)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.view.InsetsController.$r8$lambda$meqKUiuVHZJFS86fhQQzBBmdABw(Unknown Source:0)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.view.InsetsController$$ExternalSyntheticLambda10.run(D8$$SyntheticClass:0)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:942)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8516)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
02-21 12:28:00.908 31609 31609 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: FATAL EXCEPTION: main
02-21 12:29:32.715 31846 31846 E AndroidRuntime: Process: xyz.zedler.patrick.grocy.nightly.debug, PID: 31846
02-21 12:29:32.715 31846 31846 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'float androidx.core.view.WindowInsetsAnimationCompat.getInterpolatedFraction()' on a null object reference
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.util.UiUtil$1.onProgress(UiUtil.java:334)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at androidx.core.view.WindowInsetsAnimationCompat$Impl30$ProxyCallback.onProgress(WindowInsetsAnimationCompat.java:1072)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.view.View.dispatchWindowInsetsAnimationProgress(View.java:12173)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7624)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7630)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7630)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7630)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7630)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7630)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.view.ViewRootInsetsControllerHost.dispatchWindowInsetsAnimationProgress(ViewRootInsetsControllerHost.java:108)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.view.InsetsController.lambda$new$3(InsetsController.java:818)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.view.InsetsController.$r8$lambda$meqKUiuVHZJFS86fhQQzBBmdABw(Unknown Source:0)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.view.InsetsController$$ExternalSyntheticLambda10.run(D8$$SyntheticClass:0)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:942)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8516)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-21 12:29:32.715 31846 31846 E AndroidRuntime: 	at com.android.internal.os.RuntimeI
```

**Comment by patzly** [comment]
@YoMamasNerd That's good to hear :D 
I've built a new nightly build with a small change, can you please test it?

**Comment by patzly** [comment]
@YoMamasNerd Oh sorry! Please test the master nightly, I haven't merged it yet :)

**Comment by patzly** [comment]
@YoMamasNerd That's perfect! The last fix was important, else you would had another exception in the crashlog so all good now :)
