### ISSUE TITLE
Consuming items throws Network error 

### ISSUE THREAD

**Issue by YoMamasNerd** [patzly/grocy-android#834]
When consuming an item the app displays a network error. But only when using the consume option with text and icon. Using the consume option with just the icon everything works as expected.

[Video to reproduce](http://sync.hometopf.de/f/0099db65202448a5a453/)

```
Netzwerkfehler

com.android.volley.ClientError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:281)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:62)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:6)

```

**Comment by dominiczedler** [comment]
Thanks, I will look into it soon - but I cannot promise that I'm able to reproduce it if it is one of the more complex bugs. :) I will try my best.

**Comment by lukepdunwell-student** [comment]
Actually, consuming after scanning a barcode throws a network error in my case, too, but ONLY if i try to consume more than is in stock
