### ISSUE TITLE
Network error when moving with grocy code

### ISSUE THREAD

**Issue by Saturo78** [patzly/grocy-android#894]
When I try to move a stock entry with grocy code I get a network error:

`Netzwerkfehler

com.android.volley.ClientError
	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:193)
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
`

**Comment by Saturo78** [comment]
I have now found out when this error occurs.
If a stock entry is not in the standard storage location, the standard storage location is still pre-assigned in the transaction and leads to this error.
The current stock location of the scanned grocy code stock entry must always be used here.
